
name: flutter_tflite_app
description: A simple Flutter app using TensorFlow Lite.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.1.2

flutter:
  assets:
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/labels.txt
